apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  annotations:
    security.opendatahub.io/enable-auth: "true"
  name: nemo-simple
spec:
  env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          key: token
          name: api-token-secret
    - name: MAIN_MODEL_BASE_URL
      value: "https://$YOUR_ENDPOINT/v1"
    - name: MAIN_MODEL_ENGINE
      value: "openai"
  nemoConfigs:
    - configMaps:
        - nemo-simple-config
      name: nemo-simple-config
  replicas: 1
