kind: ConfigMap
apiVersion: v1
metadata:
  name: nemo-simple-config
data:
  config.yaml: |
    models:
      - type: main
        engine: openai
        parameters:
          openai_api_base: "https://$YOUR_ENDPOINT/v1"
          model_name: "gemma4-31b-nvfp4"
          api_key: EMPTY
    rails:
      config:
        sensitive_data_detection:
          input:
            entities:
              - EMAIL_ADDRESS
              - PERSON
          output:
            entities:
              - PERSON
      input:
        flows:
          - mask sensitive data on input
      output:
        streaming:
          enabled: True
        flows:
          - mask sensitive data on output
  rails.co: |
    # Using built-in sensitive data detection rails
    define bot refuse to respond
      "申し訳ありません。その質問に回答することはできません。"
